stages:
  - build
  - package

build_project:
  stage: build
  image: node:latest  # 使用最新的 Node.js 镜像
  script:
    - cd frontend  # 进入项目前端目录
    - npm install  # 安装依赖
    - npm run build  # 执行构建命令
  artifacts:
    paths:
      - frontend/dist/  # 将构建后的 dist 目录作为工件

package_project:
  stage: package
  script:
    - cd frontend/dist  # 进入构建后的 dist 目录
    - zip -r ../project-release.zip .  # 将 dist 目录打包为 zip 文件
  artifacts:
    paths:
      - frontend/project-release.zip  # 将打包后的 zip 文件作为工件